### ISSUE TITLE
Version 2.6

### ISSUE THREAD

**Issue by kessilover** [mobolic/facebook-sdk#283]
I keep installing the new facebook-sdk but it always leaves the added version 2.6.

**Comment by martey** [comment]
Your questions confused me initially, but I think that you are asking why support for Graph API version 2.6 is not available when you install facebook-sdk.

If this is the case, it is because the most recent version (1.0.0) was released **before** Graph API 2.6 was released. To use any of Graph API 2.6's features, you will want to [install the SDK from Git](https://facebook-sdk.readthedocs.io/en/latest/install.html#installing-from-git).

Questions like this are better suited to [our Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook), which you should join! I will post a more detailed explanation of the different versions (and why you might want to install them) there soon.

**Comment by kessilover** [comment]
Problem is that thr e installation doesn't go through when I ran the
setup.py file
nothing happens.

**Comment by martey** [comment]
Can you describe the commands that you are using to install, including any error messages you are seeing?

**Comment by kessilover** [comment]
Python3 "the path to the setup file" install

**Comment by martey** [comment]
That doesn't include any error messages...

I just tested this. It didn't work with "the path to the setup file", but it did work by traversing to the "facebook-sdk" directory and running "python setup.py install".

Since using pip and virtualenv is the preferred way of installing this SDK (like most other Python packages), I don't think that this is a serious bug.
