### ISSUE TITLE
request method does not use explicit Graph API version

### ISSUE THREAD

**Issue by yotammanor** [mobolic/facebook-sdk#284]
`graph.request()` does not pass the api version in the way facebook expects it to, for version 2.6 at least.

explicitly:

graph.request does: `https://graph.facebook.com/<path>?<args>` etc.
Facebook expects: `https://graph.facebook.com/<VERSION>/<path>?<args>` etc.

The bug might be different but this is what I deduced so far.
Thanks!

**Comment by martey** [comment]
Can you post the error message you are getting when you use `https://graph.facebook.com/<path>?<args>`?

**Comment by martey** [comment]
I think I understand the issue now - the `request` method doesn't use `GraphAPI.version` like other higher level methods like `get_object` or `put_object`.

This is intentional. Making `request` versioned would cause bugs (see e3a7c11ac1c984612df9edfce57f3b6a39b6a9e0) and make it more difficult to use the method to call different versions of the API.
