### ISSUE TITLE
Use of since parameter

### ISSUE THREAD

**Issue by rogeriobiondi** [mobolic/facebook-sdk#299]
Hello,

I have a question regarding the SDK
I'm testing the example https://github.com/mobolic/facebook-sdk/blob/master/examples/get_posts.py and it's very fine. Is it possible using the "since" parameter in order to filter the posts after a specific date/time? How this parameter could be accomplished by the facebook-sdk? Thank you very much.

Best regards,
Rogerio

**Comment by rogeriobiondi** [comment]
I've tried this:

import time
import datetime
d = datetime.date(2016,7,10)
timestamp = time.mktime(d.timetuple())
profile = graph.get_object(user, since=timestamp)

But without success.
Thank you.

**Comment by martey** [comment]
Hi,

Since this is a question and a bug report, it would be better suited for [the project's Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook) instead of this issue tracker. Not only are there more people subscribed to the Google Group than there are watching this repository, but the Google Group makes it easier for future people with the same or similar issues to find information.

I would advise you to post a message there. It would be a great idea to include what versions of the library/SDK and Graph API you are using, as well as any errors that the Graph API is sending you.

**Comment by rogeriobiondi** [comment]
Thank you very much, martey.

Best regards,
Rogerio
