### ISSUE TITLE
GraphAPIError: (#200) The user hasn't authorized the application to perform this action

### ISSUE THREAD

**Issue by awaisdar001** [mobolic/facebook-sdk#312]
I am using python2.7 and facebook-sdk--2.0.0. I have obtained my short/long lived token from facebook. When I do not specify a version it uses the default version which is 2.0 and it works fine and posts successfully on the page wall.

I changed to version to 2.5 and with that, I started getting the following error message.

```
 return self.api.put_wall_post(msg, attachment=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/facebook/__init__.py", line 163, in put_wall_post
    **attachment)
  File "/usr/local/lib/python2.7/dist-packages/facebook/__init__.py", line 144, in put_object
    method="POST")
  File "/usr/local/lib/python2.7/dist-packages/facebook/__init__.py", line 272, in request
    raise GraphAPIError(result)
GraphAPIError: (#200) The user hasn't authorized the application to perform this action
```

**Code**
```
attachment = {'link': 'www.foo.bar/view/foobar', 'picture':'www.foo.bar/foobar.jpg'}
api = facebook.GraphAPI(access_token=self.cfg['page_access_token'], version=2.5)
api = put_wall_post("my page post", attachment=kwargs)  # this fails.
```
```

api = facebook.GraphAPI(access_token=self.cfg['page_access_token'])
api = put_wall_post("my page post", attachment=kwargs) # Works
```

**Token Information**
**Scopes:** `manage_pages, business_management, publish_actions, public_profile`

**Origin** `Web`

**Valid**  `True`

**Expires** `Never`

**Issued**  `1463252518 (about 4 months ago)`

How can I fix the problem for v2.5 or what I might be doing wrong?

**Comment by martey** [comment]
Since facebook-sdk doesn't automatically manage Facebook application permissions, it is likely this is the results of changes in the Graph API - see https://developers.facebook.com/docs/apps/changelog.

I am closing this issue since this does not seem to be a bug in the library. If you find information that suggests otherwise, please feel free to comment here. Otherwise, general questions or discussion about using the Graph API with Python are better suited to the Google Group at https://groups.google.com/forum/#!forum/pythonforfacebook.

**Comment by joukes** [comment]
Still a "bug" in 2021
