### ISSUE TITLE
Add "Request Method" to get_object method

### ISSUE THREAD

**Issue by paladini** [mobolic/facebook-sdk#345]
[Facebook recommends to use a POST as the request method when you're dealing with large requests](https://developers.facebook.com/docs/graph-api/using-graph-api#largerequests), something that could help a lot of developers that use this lib.

I've checked the documentation and submitted issues but I haven't found a way to use some method like "get_object" using another request method than the regular GET. Is it possible to implement something like that in order to suport large requests?

Thanks for the lib!

**Comment by martey** [comment]
It makes my life significantly easier if you submit questions to the [Google Group](https://groups.google.com/forum/#!forum/pythonforfacebook) instead of asking them in issues here.

Right now, you can use the `request` method directly. I would probably not be opposed to a pull request that added optional POST support to other methods.
