### ISSUE TITLE
get_object fails for objects with "?" in it (e.g. URLs with query string params)

### ISSUE THREAD

**Issue by bcipolli** [mobolic/facebook-sdk#354]
**Steps to reproduce:**

1. Call `get_object` on a URL with querystring parameters (e.g. http://fundraise.teamrubiconusa.org/fundraise/get-involved?cid=5643)

**Expected Outcome:**

Correct likes (currently: 20)

**Current behavior:**

Some other number.

**Notes:**

* `get_object` is directly putting the object ID into the URL. This is incorrect; the object ID can contain URL-relevant characters, and so must be URL encoded.
* I've confirmed that if the *user* URL encodes the ID, that things are fixed. `get_object` should do this for the user, I believe.

**Comment by martey** [comment]
> This is incorrect; the object ID can contain URL-relevant characters, and so must be URL encoded.

I'm worried about unintended consequences of automatically URL encoding all IDs entered into `get_object`, especially since object IDs do not have to be (and are not in most cases) valid URLs.

While I do not think `get_object` should be modified, I will try and update the function's documentation to make it clearer that URLs need to be encoded if they are used.
