### ISSUE TITLE
Support GraphAPI versions > 2.7

### ISSUE THREAD

**Issue by bobwaycott** [mobolic/facebook-sdk#373]
### Version of the SDK being used

2.0.0

### Expected Behavior

Should be able to specify a valid GraphAPI version (currently, that's 2.9), and get a proper `GraphAPI` instance:

```python
> api = GraphAPI(auth_token, version='2.9')
#yay!
```

### Actual Behavior

```python
> api = GraphAPI(auth_token, version='2.9')
GraphAPIError: Valid API versions are '2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7'
```

**Comment by martey** [comment]
This isn't a bug, since support for GraphAPI v2.9 was added in #361. Version 2.0.0 does not support Graph API v2.8 or 2.9 because *it was released before these API versions existed*.

If you need access to Graph API v2.9 and can't wait for 3.0.0 to be released, you should [install from Git](https://github.com/mobolic/facebook-sdk/blob/e739a75db2dc08ba028e0788512ec528b6ec5164/docs/install.rst#installing-from-git).
