### ISSUE TITLE
Can't attach image & description when posting to wall

### ISSUE THREAD

**Issue by shaklev** [mobolic/facebook-sdk#380]
As i've seen in the 3.0.0 version there is new method available `graph.put_object` instead of the previous `graph.put_wall`.

The new method `graph.put_object` doesn't offer to attach `image` & `description` properties as `**kwargs`.
Regarding this, the previous method , also functioned without problems ( `graph.put_wall`) , but also `image` & `description` properties were not registered when sharing to wall.

Don't know if this is a problem with the library or with new changes in the facebook Graph API ?

**Comment by shaklev** [comment]
More info on the same subject: https://developers.facebook.com/docs/apps/changelog#v2_9_90_day_deprecations

**Comment by martey** [comment]
Since you didn't use the [issue template](https://github.com/mobolic/facebook-sdk/blob/master/.github/issue_template.md), I can't tell whether this is a general question about using the library or an actual bug. If you are certain it is the latter, please comment with the information that the issue template asked you to provide when creating the issue.
