### ISSUE TITLE
Reactions in version 2.7 and above

### ISSUE THREAD

**Issue by subkrish** [mobolic/facebook-sdk#382]
### Version of the SDK being used
2.0.0
### Expected Behavior
```
{
  "data": [
    {
      "id": "<id>",
      "story": "<story>",
      "created_time": "2017-08-12T01:32:25+0000",
      "reactions": {
        "data": [
        ],
        "summary": {
          "total_count": 11
        }
      }
    }
  ],
  "paging": {
    "previous": "",
    "next": ""
  }
}
```
### Actual Behavior
`facebook.GraphAPIError: (#12) Reactions read API requires version v2.6 or higher`
### Steps to Reproduce
The API version was set to 2.7 : 
`graph = facebook.GraphAPI(access_token, version = '2.7')`

```
posts = graph.request('/me/posts?fields=id,story,created_time,reactions.type(LIKE).limit(0).summary(total_count)')
```

**Comment by martey** [comment]
What is the value of  `graph.version`?

**Comment by subkrish** [comment]
The `graph.version` is `2.7`

**Comment by martey** [comment]
Hmm, I missed the fact that you were using the `request` method. See https://github.com/mobolic/facebook-sdk/issues/284#issuecomment-223185721.

**Comment by subkrish** [comment]
@martey If possible, please change the error message because it is very misleading from and enduser point of view.

**Comment by martey** [comment]
The error message isn't misleading because you were not using version 2.7 when you used the `request` method. Irregardless, I don't work at Facebook, so I can't change their error messages.

I think documenting the fact that the `request` method (unlike other methods) does not add versioning automatically should solve this issue. If you disagree, please feel free to comment in #323.

**Comment by subkrish** [comment]
@martey I feel this is good and would help devs know from the documentation that when `request` is used version `2.7` is not used.
