### ISSUE TITLE
Get likes data of a post in a facebook page

### ISSUE THREAD

**Issue by ankitarath2011** [mobolic/facebook-sdk#448]
PLEASE DELETE THE ABOVE AFTER READING IT AND FILL IN EACH OF THE FOLLOWING SECTIONS.

### Expected Behavior -  Tried fetching reactions to a post(From like section) using following. But not getting the data.
```
import facebook

graph = facebook.GraphAPI(access_token="your_token", version="3.1")

likes = graph.get_connections(id=post_id, connection_name='likes')
```

**Comment by martey** [comment]
Both this issue and #449 do not contain enough information to confirm whether this is an issue with the SDK. Since it seems likely that this is actually a question on how to use the SDK and the Graph API, I am closing these issues. Please feel free to continue using the [Google Group](https://groups.google.com/group/pythonforfacebook) for further support.
