### ISSUE TITLE
Maintenance of package

### ISSUE THREAD

**Issue by DmytroLitvinov** [mobolic/facebook-sdk#465]
Hello @martey ,

First of all thank you for library and your effort on it.

As I see there is minor activity in commits, but not so active as we would like to have.
So seems like active development on this library is finished and the maintaining of this package is abandoned. Last official release of package was on November 6, 2018.

Is there any person which you trust and he is interested in this library and he is ready to support this library(accept, review MRs, publish to PyPi etc)?

**Comment by martey** [comment]
The last commit to this library is from less than a month ago. I had planned on creating a release recently, but have been waiting in hopes that #463 could be merged.

I don't know what you mean by "not so active as we would like to have" and I disagree with your assertion that this package has been abandoned.

**Comment by AndrewPix** [comment]
@martey The overall project activity is ok, but the releases are sooo infrequent so the project can look like it is abandoned. For the past two years, we install this library from the git source instead of PyPi. And it is not very good and adds some problems to our deploy tools. We just need a release with actual GraphAPI versions and that's all. I think such libraries should have releases at least for every new GraphAPI version, shouldn't it? 

Thank you for your job!
